### ISSUE TITLE
config.vm.hostname instead of folder/path

### ISSUE THREAD

**Issue by JZubero** [fffilo/gnome-vagrant-indicator#10]
It would be great if there was an option to have the value of [config.vm.hostname](https://www.vagrantup.com/docs/vagrantfile/machine_settings.html#config-vm-hostname) as list label. I am facing the problem that I have pretty long full path strings and using only the folder names gives me double entries (like multiple "backend" entries)

**Comment by fffilo** [comment]
Soon as I find some time I’ll make it so...

**Comment by JZubero** [comment]
If you share your thoughts with me how to achieve this I'll be happy to create a pull request with a suggestion for the implementation.

**Comment by fffilo** [comment]
I'm currently working on 'machine specific config'. The idea is that each machine can have specific settings (duh), different than the ones set in preferences. Beside preferences user can set label as well.

First update extension from develop branch:

    wget https://raw.githubusercontent.com/fffilo/gnome-vagrant-indicator/master/install.sh -O - | bash -s -- develop

...and restart gnome-shell.

In each vagrant machine directory you will have `.gnome-vagrant-indicator@gnome-shell-exstensions.fffilo.github.com` file. In this file you can set your label. Note that this is still work in progress, so only label works for now.

Hope you'll be happy with this solution...

**Comment by fffilo** [comment]
Forgot to mention it: machine specific config won't take effect until you restart gnome-shell (since this is still work in progress)...

**Comment by JZubero** [comment]
Thanks for the quick feedback.

> In each vagrant machine directory you will have `.gnome-vagrant-indicator@gnome-shell-exstensions.fffilo.github.com` file. In this file you can set your label. Note that this is still work in progress, so only label works for now.

This is a fine workaround for the moment. It would be great to have this as a standard feature wired to the extension UI though. I'd really appreciate if you'd decide to go for that sometime.

**Comment by fffilo** [comment]
The `Vagrantfile` is not a configuration file, but ruby script, and there is no easy way i can correctly parse `config.vm.hostname` from it. So I decided i won't add this feature in _Preferences_. Sorry about that...

I added _machine config_ into _Preferences_ (show/hide) so you can easily open your _machine config_ from UI.

**Comment by JZubero** [comment]
OK, understood. Will you create a new official version anytime soon? I've seen those changes are in the`develop` branch only.

**Comment by pellcorp** [comment]
I tried the branch, and this does not support multi-machine images, possible to parse the output of vagrant status to name each image separately in the menu?

**Comment by pellcorp** [comment]
oh and also it would be preferred if the config were not saved to the vagrant directory, where I would have to then add exclusions for this file, so the ~/.config directory would surely be more friendly.

**Comment by fffilo** [comment]
Try new version:

    wget https://raw.githubusercontent.com/fffilo/gnome-vagrant-indicator/master/install.sh -O - | bash

...and reload gnome-shell...
