### ISSUE TITLE
Extension is broken with Gnome 3.32/3.34

### ISSUE THREAD

**Issue by Silarn** [fffilo/gnome-vagrant-indicator#11]
I know there were changes to GObject, ES6 syntax and class changes, which broke several other extensions. Not sure which particular change is breaking this.

**Comment by fffilo** [comment]
can you provide more info? error log?

**Comment by Silarn** [comment]
Well, looking glass indicates TypeError: this._construct is not a function

**Comment by Xaraxia** [comment]
I can't enable this one with gnome-tweaks, it shows a warning icon.
Relevant syslog below:
May 22 09:31:02 hostname gnome-shell[2381]: Some code called array.toString() on a Uint8Array instance. Previously this would have interpreted the bytes of the array as a string, but that is nonstandard. In the future this will return the bytes as comma-separated digits. For the time being, the old behavior has been preserved, but please fix your code anyway to explicitly call ByteArray.toString(array).#012(Note that array.toString() may have been called implicitly.)#0120 parse() ["/home/username/.local/share/gnome-shell/extensions/gnome-vagrant-indicator@gnome-shell-exstensions.fffilo.github.com/vagrant.js":203]#0121 wrapper() ["resource:///org/gnome/gjs/modules/_legacy.js":82]#0122 _init() ["/home/username/.local/share/gnome-shell/extensions/gnome-vagrant-indicator@gnome-shell-exstensions.fffilo.github.com/vagrant.js":389]#0123 wrapper() ["resource:///org/gnome/gjs/modules/_legacy.js":82]#0124 _Base.prototype._construct() ["resource:///org/gnome/gjs/modules/_legacy.js":18]#0125 newClass() ["resource:///org/gnome/gjs/modules/_legacy.js":114]#0126 _def() ["/home/username/.local/share/gnome-shell/extensions/gnome-vagrant-indicator@gnome-shell-exstensions.fffilo.github.com/indicator.js":74]#0127 wrapper() ["resource:///org/gnome/gjs/modules/_legacy.js":82]#0128 _init() ["/home/username/.local/share/gnome-shell/extensions/gnome-vagrant-indicator@gnome-shell-exstensions.fffilo.github.com/indicator.js":42]#0129 wrapper() ["resource:///org/gnome/gjs/modules/_legacy.js":82]#01210 enable() ["/home/username/.local/share/gnome-shell/extensions/gnome-vagrant-indicator@gnome-shell-exstensions.fffilo.github.com/extension.js":40]#01211 enableExtension() ["resource:///org/gnome/shell/ui/extensionSystem.js":131]#01212 loadExtension() ["resource:///org/gnome/shell/ui/extensionSystem.js":177]#01213 _loadExtensions/<() ["resource:///org/gnome/shell/ui/extensionSystem.js":324]#01214 _emit() ["resource:///org/gnome/gjs/modules/signals.js":128]#01215 _loadExtension() ["resource:///org/gnome/shell/misc/extensionUtils.js":251]#01216 scanExtensions/<() ["resource:///org/gnome/shell/misc/extensionUtils.js":257]#01217 collectFromDatadirs() ["resource:///org/gnome/shell/misc/fileUtils.js":25]#01218 scanExtensions() ["resource:///org/gnome/shell/misc/extensionUtils.js":256]#01219 _loadExtensions() ["resource:///org/gnome/shell/ui/extensionSystem.js":326]#01220 enableAllExtensions() ["resource:///org/gnome/shell/ui/extensionSystem.js":334]#01221 _sessionUpdated() ["resource:///org/gnome/shell/ui/extensionSystem.js":365]#01222 init() ["resource:///org/gnome/shell/ui/extensionSystem.js":373]#01223 _initializeUI() ["resource:///org/gnome/shell/ui/main.js":218]#01224 start() ["resource:///org/gnome/shell/ui/main.js":127]#01225 <TOP LEVEL> ["<main>":1]

May 22 09:31:02 hostname gnome-shell[2381]: Extension "gnome-vagrant-indicator@gnome-shell-exstensions.fffilo.github.com" had error: TypeError: this._construct is not a function

**Comment by Silarn** [comment]
I have some updates at https://github.com/Silarn/gnome-vagrant-indicator that restores much of the functionality, however I'm having trouble getting the submenu to open for the listed boxes. I haven't quite figured the issue out yet.

It does appear to be parsing the vagrant status correctly, as I see the up/down indicator in the menu. I just can't open the submenu to select any futher options.

**Comment by Silarn** [comment]
It was due to a change in how bindings are handled for non-GObject classes. This is fixed with my last commit and should be mergable.

**Comment by Silarn** [comment]
3.34 broke the extension again, I have a WIP branch to fix this. It largely comes down to various PopupMenu classes being converted to GObject syntax. Updating these definitions has allowed the extension to run but it's not handling events correctly yet.

https://github.com/Silarn/gnome-vagrant-indicator/tree/3_34_compat

**Comment by Silarn** [comment]
I've created PR #14 to fix compatibility with 3.34.

**Comment by fffilo** [comment]
Try new version:

    wget https://raw.githubusercontent.com/fffilo/gnome-vagrant-indicator/master/install.sh -O - | bash

...and reload gnome-shell...

**Comment by Silarn** [comment]
Strangely, this seemed to work for me initially, but now it's crashing again. My fork is still working.

**Comment by Silarn** [comment]
I've updated my pull request with the latest changes to master.
