### ISSUE TITLE
Multi Machine vagrant files not properly supported

### ISSUE THREAD

**Issue by pellcorp** [fffilo/gnome-vagrant-indicator#12]
I use a lot of multi-machine vagrant files and it would be good if these were properly supported

**Comment by pellcorp** [comment]
actually maybe this will be supported by another issue

**Comment by pellcorp** [comment]
SSH does not work, I get this error:
This command requires a specific VM name to target in a multi-VM environment.

The machine labels are not displayed, just the folder name duplicated for each image

**Comment by fffilo** [comment]
i'll take a look at this as soon as i find some time...

**Comment by fffilo** [comment]
Try new version

    wget https://raw.githubusercontent.com/fffilo/gnome-vagrant-indicator/master/install.sh -O - | bash

**Important**: indicator does not work with gnome 3.32/3.34 (will fix this asap)
