### ISSUE TITLE
TypeError: this.list is null

### ISSUE THREAD

**Issue by johnroach** [fffilo/gnome-vagrant-indicator#6]
Each time I click on different actions such as "halt" or "ssh" for a given vagrant box I get the following error
```
TypeError: this.list is null
```

as a pop-up.

I can see the vagrant box getting picked up and the color turns to green when vagrant box is running.

I couldn't find anything using the `journalctl -xe` command. Is this a known issue?

**Comment by fffilo** [comment]
The indicator can not get list of terminal emulators. Please execute following command in terminal

    update-alternatives --list x-terminal-emulator

...and paste the result

**Comment by johnroach** [comment]
The command you have given didn't really give much...
```
$ update-alternatives --list x-terminal-emulator
alternatives version 1.10 - Copyright (C) 2001 Red Hat, Inc.
This may be freely redistributed under the terms of the GNU Public License.

usage: alternatives --install <link> <name> <path> <priority>
                    [--initscript <service>]
                    [--family <family>]
                    [--slave <link> <name> <path>]*
       alternatives --remove <name> <path>
       alternatives --auto <name>
       alternatives --config <name>
       alternatives --display <name>
       alternatives --set <name> <path>
       alternatives --list
       alternatives --remove-all <name>

common options: --verbose --test --help --usage --version --keep-missing
```

However, I believe you wanted this:

```
$ sudo update-alternatives --list
cups_backend_smb	auto	/usr/bin/smbspool
google-chrome	auto	/usr/bin/google-chrome-stable
qtchooser-4	auto	/etc/xdg/qtchooser/4-64.conf
fakeroot	auto	/usr/bin/fakeroot-tcp
libnssckbi.so.x86_64	auto	/usr/lib64/pkcs11/p11-kit-trust.so
javac	auto	/usr/java/jdk1.8.0_151/bin/javac
whois	auto	/usr/bin/jwhois
xinputrc	auto	/etc/X11/xinit/xinput.d/ibus.conf
mkisofs	auto	/usr/bin/genisoimage
qtchooser-5	auto	/etc/xdg/qtchooser/5-64.conf
pax	auto	/usr/bin/spax
print	auto	/usr/bin/lpr.cups
java	auto	/usr/java/jre1.8.0_151/bin/java
ld	auto	/usr/bin/ld.bfd
libwbclient.so.0.14-64	auto	/usr/lib64/samba/wbclient/libwbclient.so.0.14
mta	auto	/usr/bin/esmtp-wrapper
cifs-idmap-plugin	auto	/usr/lib64/cifs-utils/cifs_idmap_sss.so
modules.sh	auto	/usr/share/Modules/init/modules.sh
qtchooser-default	auto	/etc/xdg/qtchooser/4.conf
go	auto	/usr/lib/golang/bin/go
```

**Comment by fffilo** [comment]
I guess update-alternatives way does not work on non-debian like systems. Need to find the way to get default terminal emulator on red hat, but i'm too lazy to install new virtual machine for testing ;-)

Does

    gnome-terminal

...start new terminal window on red hat?

**Comment by johnroach** [comment]
Yes it does.

**Comment by fffilo** [comment]
please update your extension from develop branch...

    wget https://raw.githubusercontent.com/fffilo/gnome-vagrant-indicator/master/install.sh -O - | bash -s -- develop

...test it and let me know.

**Comment by johnroach** [comment]
It worked!! Thank you!

**Comment by fffilo** [comment]
Glad to be helpful.
