### ISSUE TITLE
No vagrant machines found

### ISSUE THREAD

**Issue by cmmata** [fffilo/gnome-vagrant-indicator#7]
Hello,

I have just installed Gnome Vagrant Indicator, but I don't see how to use or configure it. I have a Vagrant virtual machine running, but the Indicator doesn't find it. And I don't know where does this indicator look for Vagrantfile files or how does it connect to the possible virtual machines. Do I have to do something before start using it?

**Comment by fffilo** [comment]
hi there,

first of all: do you have indicator in your gnome status area?
and if so what does it display?

second thing you can check is log (gnome-log).
does it display any gnome-vagrant-indicator error?

and to answer your question how does indicator connects to possible virtual machine: it 'listens' to ~/.vagrant.d/data/machine-index/index file...

**Comment by cmmata** [comment]
I can see the indicator in Gnome status area, and and it says `No Vagrant machines found`. I can only check its preferences dialog.

If I open Logs app and filter by `vagrant`, I can see these two lines several times:
```
JS LOG: WARNING: addSignalMethods is replacing existing [object prototype prototype of GType:GnomeVagrantIndicatorPrefsInput jsobj@(nil)] emit method
JS LOG: WARNING: addSignalMethods is replacing existing [object prototype prototype of GType:GnomeVagrantIndicatorPrefsInput jsobj@(nil)] disconnect method
```
And those other lines one time each one
```
Some code accessed the property 'DisplayVagrant' on the module 'menu'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Some code accessed the property 'Emulator' on the module 'vagrant'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Some code accessed the property 'CommandSystem' on the module 'vagrant'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Some code accessed the property 'CommandVagrant' on the module 'vagrant'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
```
If I filter by `gnome-vagrant-indicator`, I does not show anything.

And finally, I can see a `~/.vagrant.d/data/machine-index/index.lock` but any `index` in that folder. If I execute `vagrant status` in my projects folder, it says it's running.
```
vagrant status
Current machine states:
default                   running (virtualbox)
```

**Comment by fffilo** [comment]
please try

`echo $VAGRANT_HOME`

...in terminal

**Comment by cmmata** [comment]
It's empty, I see the .rpm installer doesn't set it. It should be `~/.vagrant.d.` as the docs say it's the default value.

**Comment by fffilo** [comment]
what about

`vagrant global-status` ?

**Comment by cmmata** [comment]
It's strange
```
➜ vagrant global-status
id       name   provider state  directory                           
--------------------------------------------------------------------
There are no active Vagrant environments on this computer! Or,
you haven't destroyed and recreated Vagrant environments that were
started with an older version of Vagrant.
```
But if I execute `vagrant status` in the project folder it says `running (virtualbox)`.

**Comment by fffilo** [comment]
well, as you can see the problem is not in indicator, the problem is in your virtual machine. try to create new vagrant machine and see changes in indicator...

**Comment by cmmata** [comment]
Yes, you're right! I was investigating about the global-status, and if there's anyone else with the same problem, you have to destroy and recreate the virtual machine as it's said in [official documentation](https://www.vagrantup.com/docs/cli/global-status.html). This comes probably because of using a virtual machine created with another vagrant version from the actual one. I have destroyed and recreated and now the indicator is working. Thank you!

**Comment by fffilo** [comment]
glad to be helpful
