### ISSUE TITLE
"Refresh" option to update boxes listed in indicator

### ISSUE THREAD

**Issue by lofidevops** [fffilo/gnome-vagrant-indicator#9]
I am a Vagrant user creating, running and deleting boxes. I want to view the latest status of all boxes, so that I can perform appropriate actions (e.g. I don't try to start a box that has just been deleted).

**Suggested solution:**

Add a "Refresh" option to the indicator dropdown. When selected it

1. Invokes `vagrant global-status --prune` (or equivalent)
2. Updates the box entries in the dropdown

**Notes:**

If I perform the following actions, the indicator is updated as expected:

```
vagrant up 25df1ae
# starts machine with given id
# no change in indicator
vagrant global-status prune
# prompts for administrator credentials
# CLI shows list of boxes
# indicator now shows that 25df1ae is running
```

**Comment by fffilo** [comment]
executing `vagrant global-status --prune` can be heavy task (if you have many boxes). i'm planning to add option in settings (yes/not toggle) to execute prune on indicator start.

**Comment by lofidevops** [comment]
That sounds like a great option!

I'd still like to suggest a *user-initiated refresh*, because it's precisely in the middle of a session that this might be useful. I guess you could hide the Refresh button in the settings dialog, so that users aren't tempted to spam it?

**Comment by fffilo** [comment]
the refresh option is not needed. refresh is automatically executed on every machine state change (by monitoring vagrant index file).

your problem is unknown machine state in issue #8. when we fix this you'll see what i'm talking about ;)

leaving this issue open for now.

**Comment by fffilo** [comment]
Added _Refresh machines status at startup_ button is _Preferences_.
